version: '3'
services:
  accounts: 
    image: followup/account
    build: account
    volumes:
      - ./account:/app
    ports:
      - 3000:3000
  accounts-db:
    image: mongo
    ports:
      - 27017:27017
    env_file: account/.env